name: Validate

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_call:

concurrency:
  group: validate-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  typecheck:
    name: "Typecheck"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Mise
        uses: caido/action-mise-action@v3.2.0
        with:
          working_directory: .
          version: ${{ vars.CI__MISE_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run typechecker
        run: pnpm typecheck

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Mise
        uses: caido/action-mise-action@v3.2.0
        with:
          working_directory: .
          version: ${{ vars.CI__MISE_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linter
        run: pnpm lint

  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Mise
        uses: caido/action-mise-action@v3.2.0
        with:
          working_directory: .
          version: ${{ vars.CI__MISE_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

  knip:
    name: "Knip"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Mise
        uses: caido/action-mise-action@v3.2.0
        with:
          working_directory: .
          version: ${{ vars.CI__MISE_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run knip
        run: pnpm knip

  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Mise
        uses: caido/action-mise-action@v3.2.0
        with:
          working_directory: .
          version: ${{ vars.CI__MISE_VERSION }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run build
        run: pnpm build
